matrix:
  include:
    - language: csharp
      mono: none
      sudo: required
      dist: xenial
      dotnet: 2.2
      script:
      - dotnet test c#/
    - language: cpp
      os: osx
      osx_image: xcode8.3
      compiler: clang
      sudo: required
      script:
       - make -C c++/
    - language: node_js
      node_js:
        - "node"
      before_script:
        - cd javascript
        - npm install
      cache:
        directories:
          - "node_modules"
      script:
        - npm test
        - npm run lint
      after_success:
        bash <(curl -s https://codecov.io/bash)
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd java
      script:
        - gradle check --info
      after_success:
        - export CODECOV_TOKEN="59ec33f8-cdb9-4acd-876e-44aaedcc5033"
        - bash <(curl -s https://codecov.io/bash)
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/