matrix:
  include:
    - language: rust
      rust:
      - 1.41.1
      cache: cargo
      script:
      - cd rust
      - cargo build --verbose --all
      - cargo test --verbose --all
    - language: python
      python:
      - "2.7"
      - "3.8"
      script:
      - cd python/interviewQs
      - python -m unittest tests
    - language: csharp
      mono: none
      sudo: required
      dist: xenial
      dotnet: 2.2
      script:
      - dotnet test c#/
    - language: cpp
      os: osx
      osx_image: xcode8.3
      compiler: clang
      sudo: required
      script:
       - make -C c++/
    - language: cpp
      os: linux
      dist: xenial
      script:
       - make -C c++/ run-coverage
      after_success:
       - export CODECOV_TOKEN="59ec33f8-cdb9-4acd-876e-44aaedcc5033"
       - gcov c++/src/*.cpp
       - bash <(curl -s https://codecov.io/bash)
      compiler: gcc
    - language: node_js
      node_js:
        - "node"
      before_script:
        - cd javascript
        - npm install
      cache:
        directories:
          - "node_modules"
      script:
        - npm test
        - npm run lint
      after_success:
        - export CODECOV_TOKEN="59ec33f8-cdb9-4acd-876e-44aaedcc5033"
        - node node_modules/nyc/bin/nyc.js report --reporter=text-lcov > coverage.lcov
        - ./node_modules/.bin/codecov
    - language: java
      dist: trusty
      jdk: oraclejdk8
      before_script:
        - cd java
      script:
        - gradle check --info
      after_success:
        - export CODECOV_TOKEN="59ec33f8-cdb9-4acd-876e-44aaedcc5033"
        - bash <(curl -s https://codecov.io/bash)
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
